# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    #paths:   
     # -'note/**/*.md'
  #pull_request:
    #branches: [ master ]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo 1---------
        homedir=`pwd`
        echo 2-------------
        mpaths=`find /home/runner/work/narule.github.io/ -name blog.json`
        echo $mpaths
        echo 3----------------
        mpaths=`find /home/runner/work/narule.github.io/ -name *`
        echo $mpaths
        echo 4-------------
        find /home/runner/work/narule.github.io -name *
        blogjson=${homedir}/html/json/blog.json
        echo $blogjson
        echo 5-----------------
        tempjson=${homedir}/html/json/temp.json
        #bloginfo=`cat ./html/json/blog.json`
        blogjson=` cat $blogjson | jq '."test" = "suc"' `
        echo $blogjson > $tempjson
        echo 6---------------
    #- name: get markdown info
      

