# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:   
      'note/**/*.md'
  #pull_request:
    #branches: [ master ]
          

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script 
      run: |
        echo Add other actions to build,
        
        homedir=`pwd`
        echo home-${homedir}
        list=`find $homedir -name *.json`
        find $homedir -name *.json
        echo ------start-----------
        blogjson=${homedir}/html/json/blog.json
        tempjson=${homedir}/html/json/temp.json
        jq '."test" = "suc1"' $blogjson
        echo get result 
        result=`jq '."test" = "suc1"' $blogjson`
        echo $result > $tempjson
        echo ----------end---------
        echo jq----
        result=`cat $blogjson | jq '."test" = "suc2"'`
        echo change-$result
        echo 6---------------
        cat $tempjson
        echo cp-------
        cp $tempjson $blogjson
        echo end ------------
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.USERNAME }}

        git add .
        git commit -m "action　up"
    #- name: get markdown info
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
          JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
         STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
         RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    
    
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.NARULE_BLOG }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        #repository: # optional, default is 
        # Destination branch to push changes
        #branch: # optional, default is master
        # Determines if force push is used
        #force: # optional
        # Determines if --tags is used
        #tags: # optional
        # Directory to change to before pushing.
        #directory: # optional, default is .
    

