name: jekyll

on:
  push:
    branches: [ master ]
    paths: '**/*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Jekyll Actions
        uses: helaili/jekyll-action@2.0.3
        with:
          # The Jekyll website source directory
          jekyll_src: ./# optional
          github_token: ${{ secrets.NARULE_BLOG }}  
